# Generated by Django 3.2.7 on 2021-10-25 11:43

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(upload_to=pathlib.PurePosixPath('/Users/titi/Desktop/P9/media/profile'), verbose_name='Photo de profil'),
        ),
    ]
