# Generated by Django 3.2.7 on 2021-11-09 17:29

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to=pathlib.PurePosixPath('/Users/titi/Desktop/P9/media/profile'), verbose_name='Photo de profil'),
        ),
    ]
