# Generated by Django 3.2.7 on 2021-11-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='profile/', verbose_name='Photo de profil'),
        ),
    ]
